[package]
name = "multi-threading-read-write-lock"
version = "0.1.0"
authors = ["“Wison Ye” <wisonye@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
names = "0.11.0"
